[transforms.trf_json]
  type = "json_parser"
  inputs = ["log_json"]
  drop_invalid = false
  drop_field = true
  field = "message"

[sinks.erasearch]
  type="elasticsearch"
  inputs = ["trf_json"]
  endpoint="${ERASEARCH_URL}"
  healthcheck.enabled = false
  mode = "bulk"
  bulk.index = "${ERASEARCH_INDEX}"

[sinks.erasearch.request]
  concurrency = "adaptive"

[sinks.erasearch.request.headers]
  #ERASEARCH_AUTH in the form of "Bearer <YOUR_API_KEY>" for cloud.era.co
  #ERASEARCH_AUTH in the form of "Basic <base64 username:password>" for basic Authorization
  Authorization = "${ERASEARCH_AUTH}"
